version: "3"

services:
  proxy:
    image: nginx:alpine
    container_name: twitfix_proxy
    volumes:
      - "./twitfix_proxy.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 8088:80
    depends_on:
      - twitfix

  twitfix:
    image: twitfix
    build: .
    container_name: twitfix_main
    volumes:
      - "./twitfix.ini:/twitfix/twitfix.ini:ro"
      - "./config.json:/twitfix/config.json:ro"
    depends_on:
      - db

  db:
    image: mongo:5.0.9
    container_name: twitfix_db
    volumes:
      - "./db:/data/db"

